language: python
python: 3.5
install:
- pip install tox
- pip install -r requirements.txt
script:
- tox -e $TOX_ENV
env:
- TOX_ENV=py26
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=py35
- TOX_ENV=pypy
- TOX_ENV=pypy3
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=coverage
after_success: coveralls
deploy:
  edge: true
  provider: pypi
  user: cordell.evan@gmail.com
  password:
    secure: eQTPKegXCUibTSN8Bwk8rKZGi68yNWXak7447k00gIprV0IydKeSR/W66kN+pKJB+7rA5pW1wSzbQ03RyqL9H9a9FdXCBKfucWI82Q/f55ZQWVFlx3tj9UCdl6hxhbowzJcU1QLKFvbDTiSuowO6Z3dbpiSBwYxvEji/qb6IeFStWPfCyQXOM4hZsg+2DcAziUWyA2TuOnHBZkh7sRrle1ph7yALSHCJGEkGuQcDbkDpUW+HOeyjnfQ713vyKeywnEGIqMLXQf0djrn2+cNzGWM3pA2jCjPkY8FXUSRjR4czaAW+EZ07GhRVWC1xT2wIARrYasjwMm0AFczkgRGejnSeVTz7OTOjoPiB2M0gGD8e9KbvwtGkSfjtxYq7skqaDKLi89IvkvnPPgkmScKz10w5EnQ3wNVQmYqBXhdg67TJ7zcxSWeo+QHjEk7Na6AnThdaAmKYu+51muGMKCxGNGeOfMzU4DlYSDEwXws9Mf12rFO5irAqbFiUz3oyBbLqckpO+dFvnXle1iQwP4Z3w54es6zIwh5aW7McBhTQ+ivxp0ZKDUvtJStnyABSpkUlaY03pRVmMc7gYwmxrna1O8bnwj5QQ9rP19UaDJZV5k8ESJkHILqeCC90rAVWCQ5F5/b8sGt/hWGEI5ThqsM8gQY5Y+/MsG08A7wjbQbyVVo=
  on:
    tags: true
    repo: ecordell/syncgateway-admin-client
    distributions: "sdist bdist_wheel"
    condition: $TOX_ENV = py35 # only deploy once
