language: python
python: 3.5
install:
- pip install tox
- pip install -r requirements.txt
script:
- tox -e $TOX_ENV
env:
- TOX_ENV=py26
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=py35
- TOX_ENV=pypy
- TOX_ENV=pypy3
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=coverage
after_success: coveralls
deploy:
  provider: pypi
  user: ecordell
  password:
    secure: Ku6rxAssmVcoQwZYtPB1G7nJ4sNq/TEtDArNs0tcz+QBAmU2mjhjtUDetXy+Xt1dN+NM4bN9R4BCJ52VmtuI4i/areLfCaNnUXtPDk06EK+SQp/cf+RavtWSsQ+m5T1gLOyx88GCJClxXVPxQ447b6o+fJDT+sQ9PwoyP/ZDt9LqL7UA0vzgb4dC1MtbeHWPc7n2Tuo57HQ/fpKjDiNeoc6dIt8OFMJXEu85kT81vDdnozqAVna3bBkLRTtAXnvRn+2CKa3/WbRRhkkO0LQh843KCybjuYBtidNiI38ZHmtJmk+YHU2n7xyfDglgoNCnWsmrb1hz17nmo96wzfRArkUMtVxPW4rDbnoQWBJZr9jCV+EF8eaZD+GqpgVFcsEfDOFlGN7vPSfSgPOISQ2hCYqUXdrBU1L6JPD0gQ0pjrtZIRlYViG5I3NzIa3FmDLHu0TLpY6u/8bVxhl8pKtOhT+jJVop5jmHZ2SjsP13t4hekD1n5RsZKBDldOrg3iNo6G5dUO1aTy9CleI9x1Mzr7Dy1DV/GO086Fc3w+omaDqvg3f9ajgX6AyObfUnrmuYFwEiTCwJ/BrXJ2DDr1bLKIzCH5LEAXU5FZdnueQ/JpEfQmhMR6IVJ7flDDJLLKBzuvUfpWzo1QYwcMuHYiM0yGyTaZC49MJQJ1NYsISGjWE=
  on:
    tags: true
    repo: ecordell/syncgateway-admin-client
    distributions: "sdist bdist_wheel"
    condition: $TOX_ENV = py35 # only deploy once
