language: python
python: 3.5
install:
- pip install tox
- pip install -r requirements.txt
script:
- tox -e $TOX_ENV
env:
- TOX_ENV=py26
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=py35
- TOX_ENV=pypy
- TOX_ENV=pypy3
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=coverage
after_success: coveralls
deploy:
  provider: pypi
  user: ecordell
  password:
    secure: C2swANJlWWhkfBbBrbzY3IDJEFZqHn7G20UgSjTYyH9rBKQ99KG7U0iQrwV/RptgS+nNP5HmIItLSTYduR3Mq70fX0ft3XHJUOIn7IZww8nFJmIrgVqLgP5fXxOGaWdddciIhe1Og8SEEWelwLWa/Ql8/I/Pchp89OySIeqCb6BmEcumjde8ItE8GPmVBCBp0lErAR5WLLzFz/xPNVXdTceD7hILTSzihieEYtpI0DJcTDlf7ZiIqSdUvYk4CYqi4aHZeCtVxCVnAnRfTX+7NCD2EpKBmA+kFk1X5v7FGgIlcW558nhHYLwlGOrq9Mbcvew2GZXNEgZ255Ds4LvEpQ5FrJthJWxXI6WlVDmssL+E/HUAZ8VgQ5GZeWnErKWZeGJgj4ltsvcghP83Fy3s32HzeJR1iUbsh4z3LoiUF/cZbQ+57r+0DBXhY+dj9dTxBJZwxQTvqQAcJd8YywPXqxSbjMRLtpauw1MidQk0ksm1o1PUDPXHX63WME9PM4mkHTtiNUSrIbMEUsCwJZAcdXjm/nk8m9N7diB7CsOe0pA4MZ2OfA6Z0GDJQ8sPveggDACYCse1n9Jucb1wdgiwKeCY65PZadshLv1qkUFi0h0MlTdl06WpD/wOTPzbc03HWEdh9zBJY9gHRYJ5EGOK+nHK2S4QkfHPZxzHEm7Qai0=
  on:
    tags: true
    repo: ecordell/syncgateway-admin-client
    distributions: "sdist bdist_wheel"
    condition: $TOX_ENV = py35 # only deploy once
