language: python
python: 3.5
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=pypy3
  - TOX_ENV=docs
  - TOX_ENV=flake8
  - TOX_ENV=coverage
after_success: coveralls
